### ISSUE TITLE
pg_regress is missing in the PostgreSQL 17 installer

### ISSUE THREAD

**Issue by arkhipov** [EnterpriseDB/edb-installers#188]
I just came across the issue that `pg_regress` is no longer provided within the EDB installer starting with the version 17. This prevents using the Windows installer in CI for testing extensions.

**Comment by dpage** [comment]
The PostgreSQL build system no longer considers pg_regress.exe to be something that should be installed. I don't know if this is intentional or not, but it's almost certainly the result of the change to Meson for the build system. 

We simply package whatever PostgreSQL's build system installs, so this is not a bug in the edb-installers project.

**Comment by arkhipov** [comment]
Thank you. This is really weird because pg_regress is included in Linux packages.

**Comment by dpage** [comment]
Most (all?) Linux packages likely still use the old autotools build system and haven't yet moved to Meson. On Windows Meson is the only option for a VC++ build now as the old MSVC build system has been removed.

**Comment by muralikrishna05** [comment]
Hi @arkhipov 
In PG17 pg_regress is located in **C:\Program Files\PostgreSQL\17\lib\pgxs\src\test\regress** directory due to Meson change. In PG16 it is located in **C:\Program Files\PostgreSQL\16\bin** directory.
