### ISSUE TITLE
add support for pl/python linked to version 3.12

### ISSUE THREAD

**Issue by tizytissy** [EnterpriseDB/edb-installers#91]
Your language pack offers for python the version 3.7, which reaches his end-of-life more the four months ago. In the meanwhile, python releases 5 main versions, the latest being 3.12.
The same applies for perl (which is stuck to version 5.26, "dead" more than three years ago).
Have you any plan to update your language pack to the newest versions?
Thank you very much in advance.

**Comment by dpage** [comment]
The language pack should be updated with each major release of PostgreSQL (though, we have been lax in doing so in the past for which I apologise). We do not upgrade outside of major versions of PostgreSQL as that could require users to rewrite parts of their procedural language code in order to apply a minor PostgreSQL upgrade which may include security fixes that should be installed promptly.
